---

- hosts: webservers

  vars_prompt:
  - name: user_passwd
    prompt: Enter regular user password
    private: yes
    confirm: yes
    encrypt: sha512_crypt
    
  roles: 
    - common

  vars:
    new_users: # Specify here usernames you want to create on the remote hosts.
      - newuser
      
    regular_user:
      - reguser