---

- hosts: webservers

  vars_prompt:
  - name: user_passwd
    prompt: Enter regular user password
    private: yes
    confirm: yes
    encrypt: sha512_crypt
    
  roles: 
    - common

  vars:
    ssh_username: # Specify here usernames you want to create on the remote hosts.
      - newuser21
      - newuser22
    reg_user:     # This is a regular user
      - reguser23