---

- hosts: servers:bastion_server

  vars_prompt:
  - name: user_passwd
    prompt: Enter regular user password
    private: yes
    confirm: yes
    encrypt: sha512_crypt

  roles: 
    - common

  vars:
    login_users:
      - bob
      - alan

    regular_user:
      - reguser