---
# tasks file for common

- name: Register host with variable
  ansible.builtin.add_host:
   name: "share_variable"
   default_key: default_key
   regular_user_key: regular_user_key

- name: Assume we have some users on remote hosts
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /bin/bash
    state: present
  become: yes
  with_items:
    - "{{ login_users }}"

- name: Generate an OpenSSH rsa keypair (2048 bits)
  community.crypto.openssh_keypair:
    path: /tmp/ssh_keys/{{ item }}
    size: 2048
  delegate_to: localhost
  with_items:
    - "{{ hostvars.share_variable.default_key }}"
    - "{{ hostvars.share_variable.regular_user_key }}"

- name: Deploy users public keys
  ansible.builtin.authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', '/tmp/ssh_keys/{{ hostvars.share_variable.default_key }}.pub') }}"
  with_items:
    - "{{ login_users }}"
  become: yes

- name: Creating regular user with password and ssh key pair.
  ansible.builtin.user:
    name: "{{ item }}"
    password: "{{ user_passwd }}"
    shell: /bin/bash
    state: present
  become: yes
  with_items:
    - "{{ regular_user }}"

- name: authorized_key
  ansible.builtin.authorized_key:
    user: "{{ item }}"
    key: "{{ lookup('file', '/tmp/ssh_keys/{{ hostvars.share_variable.regular_user_key }}.pub') }}"
  with_items:
    - "{{ regular_user }}"
  become: yes

- name: Copy private keys to bastion host
  ansible.builtin.copy:
    src: /tmp/ssh_keys/{{ hostvars.share_variable.default_key }}
    dest: /tmp/ssh_keys/
    owner: root
    group: root
    mode: '0400'
  become: yes
  when: "'bastion_server' in {{ group_names }}"

- name: Deploying a .bashrc file per user
  ansible.builtin.template:
    src: templates/bashrc.j2
    dest: "/home/{{ item }}/.bashrc"
    owner: "{{ item }}"
    group: "{{ item }}"
    force: yes
  with_items:
    - "{{ login_users }}"
    - "{{ regular_user }}"
  become: yes

- name: Limit DNS traffic to {{ dns1 }} and {{ dns2 }}
  ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    state: present
    no_extra_spaces: yes
    section: main
    option: dns
    value: none
    owner: root
    group: root
    mode: 0644
  become: yes
  notify:
    - reload network

- name: Deploy resolv.conf template
  ansible.builtin.template:
    src: templates/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  notify:
    - reload network

- name: Ensure that iptables is installed, configured and persisted across reboots
  ansible.builtin.yum:
    name: 
      - iptables-services
      - iptables
    state: latest
  become: yes
  # when: ansible_os_family == "RedHat"
  notify:
    - reload iptables

- name: "Outbound: DNS traffic to 1.1.1.1 and 1.0.0.1"
  ansible.builtin.iptables:
    chain: OUTPUT
    source: "{{ item }}"
    protocol: tcp
    destination_port: "{{ dns_port }}"
    jump: ACCEPT
  with_items:
    - "{{ dns1 }}"
    - "{{ dns2 }}"
  become: yes
  notify:
    - save iptables
    - reload iptables

- name: "Outbound: HTTPS traffic on port 443 to anywhere"
  ansible.builtin.iptables:
    chain: OUTPUT
    destination_port: "{{ https_port }}"
    protocol: tcp
    jump: ACCEPT
  become: yes
  notify:
    - save iptables
    - reload iptables

- name: "Inbound: SSH traffic on port 22 from anywhere"
  ansible.builtin.iptables:
    chain: "{{ item }}"
    protocol: tcp
    destination_port: "{{ ssh_port }}"
    jump: ACCEPT
  become: yes
  with_items:
    - "{{ iptables_chain }}"
  notify:
    - save iptables
    - reload iptables
- name: "Inbound: related traffic to permitted outbound requests"
  ansible.builtin.iptables:
    chain: "{{ item }}"
    ctstate: NEW,ESTABLISHED,RELATED
    jump: ACCEPT
  become: yes
  with_items:
    - "{{ iptables_chain }}"
  notify:
    - save iptables
    - reload iptables
    
- name: Change iptables policys to DROP
  ansible.builtin.iptables:
    chain: "{{ item }}"
    policy: DROP
  become: yes
  with_items:
    - "{{ iptables_chain }}"
  notify:
    - save iptables
    - reload iptables

